name: Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Python
      run: |
        python3 --version || true
        which python3 || true

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: 'ShalukhoDarya/robot_framework'
        ref: 'main'

    - name: Setup Python Environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Firefox version
      run: firefox --version

    - name: Install GeckoDriver
      run: |
        GECKO_DRIVER_VERSION=`curl -sS https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")'`
        wget https://github.com/mozilla/geckodriver/releases/download/$GECKO_DRIVER_VERSION/geckodriver-$GECKO_DRIVER_VERSION-linux64.tar.gz
        tar -xvzf geckodriver-$GECKO_DRIVER_VERSION-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/geckodriver

    - name: Run Robot Tests on Firefox
      run: |
        source venv/bin/activate
        robot --variable BROWSER:Firefox -d results/firefox tests/

    - name: Install Google Chrome
      run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

    - name: Check Google Chrome version
      run: google-chrome --version

    - name: Install ChromeDriver
      run: |
        CHROME_DRIVER_VERSION=`curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE`
        wget https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run Robot Tests on Chrome
      run: |
        source venv/bin/activate
        robot --variable BROWSER:Chrome -d results/chrome tests/

    - name: Clean workspace
      if: always()
      run: |
        sudo rm -rf *