name: Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary
          if [ "${{ matrix.browser }}" = "firefox" ]; then
            wget https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz
            tar -xvzf geckodriver-v0.34.0-linux64.tar.gz
            sudo mv geckodriver /usr/local/bin/
          fi

      - name: Set up ChromeDriver
        if: matrix.browser == 'chrome'
        uses: nanasess/setup-chromedriver@master

      - name: Run tests
        env:
          BROWSER: ${{ matrix.browser }}
        run: robot --variable BROWSER:${{ env.BROWSER }} tests/*.robot

      - name: Archive test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: |
            report.html
            log.html
            output.xml