name: Robot Framework Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - uses: actions/checkout@v2

    - name: Set up Python environment
      run: |
        python3 -m venv env
        source env/bin/activate

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install robotframework
        if [ ${{ matrix.browser }} = 'chrome' ]; then
          curl https://chromedriver.storage.googleapis.com/2.41/chromedriver_mac64.zip -o chromedriver.zip
          unzip chromedriver.zip
          mv chromedriver /usr/local/bin
          rm chromedriver.zip
        else
          brew install geckodriver
        fi

    - name: Run tests
      run: |
        source env/bin/activate
        robot --variable BROWSER:${{ matrix.browser }} tests