name: Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: setup python
      uses:
            actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: install python packages
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install webdrivermanager

    - name: Update ChromeDriver
      run: |
        webdrivermanager chrome

    - name: Run tests
      run: robot tests/*.robot

    - name: Clean workspace
      if: always()
      run: |
        sudo rm -rf *