name: Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ppodgorsek/robot-framework:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Robot Tests on Chrome
      run: |
        robot --variable BROWSER:headlesschrome -d results/chrome tests/