name: Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install robotframework

      - name: Run tests
        run: robot tests/*.robot

      - name: Archive test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            report.html
            log.html
            output.xml