name: Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Python
      run: |
        python3 --version || true
        which python3 || true

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: 'ShalukhoDarya/robot_framework'
        ref: 'main'

    - name: Setup Python Environment
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Robot Tests on Chrome
      run: |
        source venv/bin/activate
        robot --variable BROWSER:Chrome -d results/chrome tests/

    - name: Run Robot Tests on Firefox
      run: |
        source venv/bin/activate
        robot --variable BROWSER:Firefox -d results/firefox tests/

    - name: Clean workspace
      if: always()
      run: |
        sudo rm -rf *
