image: python:latest

stages:
  - test

before_script:
  - pip install robotframework

run_robot_tests:
  stage: test
  script:
    - robot tests/*.robot
  artifacts:
    paths:
      - report.html
      - log.html
      - output.xml
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always