name: Robot Framework Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install robotframework
        if [ ${{ matrix.browser }} = 'chrome' ]; then
          curl https://chromedriver.storage.googleapis.com/2.41/chromedriver_mac64.zip -o chromedriver.zip
          unzip chromedriver.zip
          mv chromedriver /usr/local/bin
          rm chromedriver.zip
        else
          brew install geckodriver
        fi

    - name: Run tests
      run: |
        robot --variable BROWSER:${{ matrix.browser }} tests