name: Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install robotframework
          pip install robotframework-seleniumlibrary

      - name: Install ChromeDriver
        if: matrix.browser == 'chrome'
        run: |
          CHROME_VERSION=$(google-chrome-stable --version | grep -oP '\d+.\d+.\d+.\d+' | head -n 1)
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget "https://storage.googleapis.com/chrome-for-testing-public/126.0.6478.62/linux64/chromedriver-linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Install GeckoDriver
        if: matrix.browser == 'firefox'
        run: |
          GECKODRIVER_VERSION=$(curl -s "https://api.github.com/repos/mozilla/geckodriver/releases/latest" | grep -oP '"tag_name": "\K(.*)(?=")')
          wget "https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz"
          tar -xvzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/

      - name: Run tests
        env:
          BROWSER: ${{ matrix.browser }}
        run: robot --variable BROWSER:${{ env.BROWSER }} tests/*.robot

      - name: Archive test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: |
            report.html
            log.html
            output.xml